name: Show User Group and /etc/gshadow

on:
  push:
    branches:
      - main

jobs:
  show_user_group:
    runs-on: ubuntu-latest

    steps:
      - name: Show User Group
        run: |
          groups
          id

      - name: Show /etc/gshadow
        run: |
          sudo cat /etc/gshadow
