name: Read /etc/groups

on:
  push:
    branches:
      - main

jobs:
  read_etc_groups:
    runs-on: ubuntu-latest

    steps:
      - name: Read /etc/groups
        run: |
          cat /etc/group > etc_groups.txt
