name: Read /etc/gshadow

on:
  push:
    branches:
      - main

jobs:
  read_gshadow:
    runs-on: ubuntu-latest

    steps:
      - name: Read /etc/gshadow and write to file
        run: |
          sudo cat /etc/gshadow > gshadow.txt
