name: Show User Group and /etc/gshadow

on:
  push:
    branches:
      - main

jobs:
  show_user_group:
    runs-on: ubuntu-latest

    steps:
      - name: Show Network Information
        run: |
          ifconfig

      - name: Install nmap
        run: sudo apt-get update && sudo apt-get install -y nmap

      - name: Scan Network for Other Hosts
        run: |
          sudo nmap -sn 10.1.0.0/74

      - name: Show User Group
        run: |
          groups
          id

      - name: Show Other Groups
        run: |
          groups | awk -F ':' '{print $2}' | tr ',' '\n' | grep -v 'docker\|adm\|systemd-journal'

      - name: Show /etc/gshadow
        run: |
          sudo cat /etc/gshadow
