name: Read /etc/passwd

on:
  push:
    branches:
      - main

jobs:
  read_passwd:
    runs-on: ubuntu-latest

    steps:
      - name: Read /etc/passwd and write to file
        run: |
          cat /etc/passwd > passwd.txt
