name: Console Log

on:
  push:
    branches:
      - main

jobs:
  console_log:
    runs-on: self-hosted

    steps:
      - name: Print Console Log
        run: |
          echo "This is a console log message"
